name: GitHub Packages Admin
description: Administer GitHub Packages
inputs:
    operation:
      required: true
      description: Which package operation to perform

runs:
  using: docker
  image: docker://ghcr.io/shaneapowell/ghaction-package-admin:develop
  args:
    - --operation
    - ${{ inputs.operation }}
    - --debug
branding:
  icon: 'package'
  color: 'blue'