name: GitHub Packages Admin
description: Administer GitHub Packages
inputs:
    operation:
      required: true
runs:
  using: docker
  image: docker://ghcr.io/shaneapowell/ghaction-package-admin:develop
  args:
    - --operation ${{ inputs.operation }}
branding:
  icon: 'package'
  color: 'blue'