name: GitHub Packages Admin
description: Administer GitHub Packages
inputs:
    action:
      required: true
runs:
  using: docker
  image: ghcr.io/shaneapowell/gh-packages-admin@DEVELOP
  args:
    - --action ${{ inputs.action }}
