name: Manual Test gh-packages-admin action

on:
  workflow_dispatch:

jobs:

  test-gh-packages-admin:

    runs-on: [ubuntu-latest]

    steps:

    - name: dryrun purge stale packages
      uses: shaneapowell/ghaction-package-admin@v0

      with:
        ghtoken: ${{ github.token }}
        operation: deletePackageVersions
        user: ${{ github.repository_owner }}
        package_type: container
        package_name: ghaction-package-admin
        exclude: metadata.container.tags[*]   .*
        summary: true


