name: RELEASE

on:
  push:
      tags:
        - v*

jobs:

  build-release-gh-packages-admin:
    uses: ./.github/workflows/_build.yml
    with:
      create_docker_image: true
      push_cache: true

